In [ ]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()

X = iris.data
y = iris.target

print(X[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [18]:
# How many flower we have
print("How many flower we have: ", X.shape[0])

# How many feature are recorded
print("How many feature are recorded: ", X.shape[1])

# How many classes you have?
print(iris.target_names)
print("How many classes you have?",len(np.unique(y)))




How many flower we have:  150
How many feature are recorded:  4
['setosa' 'versicolor' 'virginica']
How many classes you have? 3


In [20]:
# what are the smallest and largest petal lengths observe?
sepal_length = X[:, 0]
sepal_width = X[:, 1]
petal_length = X[:, 2]
petal_width = X[:, 3]

print("sepal length: ", np.min(sepal_length), " to ", np.max(sepal_length))


sepal length:  4.3  to  7.9


In [23]:
# mean value of sepal length 
print("mean value of sepal length: ", np.mean(sepal_length))

# std of sepal length
print("std of sepal length: ", np.std(sepal_length))



mean value of sepal length:  5.843333333333334
std of sepal length:  0.8253012917851409


In [ ]:
# mean value of sepal length for every single class
setosa = X[y == 0]
versicolor = X[y == 1]
virginica = X[y == 2]
print("mean value of sepal length for every single class")



1. which species has the longest petal on average?
2. which species has the shortest petal on average?
3. which feature varies the most?
4. which species easiest ti distinguish?
5. if you had a classify flowers using only one feature, which would you choose and why?

avfard@gmail.com
