## 1. Problem and learning goals

A researcher needs arrays with **predictable values, dimensions and data types** before performing numerical calculations.

**Tasks from the slides**
1. Create a complex-valued array containing ten 8s.
2. Generate values from 0 to 40 in steps of 8.
3. Reshape twelve sequential values into a matrix of shape `(3, 4)`.
4. Select the **second row** and all values **greater than 6**.

**Deliverable:** Show the arrays, their shapes and the filtered results. This notebook requires **NumPy**.

## 2. Import NumPy

`np` is the standard alias for NumPy. A NumPy `ndarray` is designed for efficient, element-wise numerical operations and usually stores elements of one data type.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.6


## 3. Task 1 — Create ten complex-valued 8s

`np.full(shape, fill_value, dtype=...)` creates an array filled with a chosen value. `dtype=complex` represents each 8 as `8+0j` (real part 8, imaginary part 0).

Here the shape argument is `10`, so the result is **one-dimensional**, with ten elements.

In [2]:
complex_a = np.full(10, 8, dtype=complex)

print("Complex array:", complex_a)
print("Shape:", complex_a.shape)
print("Number of dimensions:", complex_a.ndim)
print("Data type:", complex_a.dtype)
print("Element count:", complex_a.size)

assert complex_a.shape == (10,)
assert complex_a.dtype.kind == "c"  # 'c' means a complex numeric dtype
assert np.all(complex_a == 8 + 0j)

Complex array: [8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]
Shape: (10,)
Number of dimensions: 1
Data type: complex128
Element count: 10


## 4. Task 2 — Generate 0, 8, 16, …, 40

`np.arange(start, stop, step)` includes the start value but **excludes the stop value**. Therefore, use `stop=41` (or any value above 40 and no greater than 48) to include 40 with step 8.

In [3]:
steps = np.arange(0, 41, 8)

print("Values:", steps)
print("Shape:", steps.shape)
assert np.array_equal(steps, np.array([0, 8, 16, 24, 32, 40]))

Values: [ 0  8 16 24 32 40]
Shape: (6,)


## 5. Task 3 — Reshape twelve values into `(3, 4)`

`np.arange(1, 13)` creates the integers 1 through 12. Reshaping changes their arrangement **without changing the number of elements**.

\[3\text{ rows}\times 4\text{ columns}=12\text{ elements}\]

The resulting matrix is:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

In [4]:
original = np.arange(1, 13)
arr = original.reshape(3, 4)

print("Original 1D array:", original)
print("Reshaped 2D array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

assert original.size == arr.size == 12
assert arr.shape == (3, 4)

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Dimensions: 2
Size: 12


## 6. Task 4a — Select the second row

NumPy indexing starts at **zero**. The second row therefore has index `1`.

`arr[1, :]` means *row 1, all columns*. Its result is a one-dimensional array: `[5, 6, 7, 8]`.

In [5]:
second_row = arr[1, :]

print("Second row:", second_row)
print("Selected shape:", second_row.shape)
assert np.array_equal(second_row, np.array([5, 6, 7, 8]))

Second row: [5 6 7 8]
Selected shape: (4,)


## 7. Task 4b — Filter values greater than 6

The comparison `arr > 6` creates a **Boolean mask** containing `True` where the condition holds and `False` elsewhere. Using that mask to index `arr` returns only matching values.

**Expected filtered result:** `[7, 8, 9, 10, 11, 12]`.

In [6]:
mask = arr > 6
filtered = arr[mask]

print("Boolean mask:\n", mask)
print("Values greater than 6:", filtered)
print("Number of matching values:", filtered.size)

assert np.array_equal(filtered, np.array([7, 8, 9, 10, 11, 12]))
assert np.all(filtered > 6)

Boolean mask:
 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
Values greater than 6: [ 7  8  9 10 11 12]
Number of matching values: 6


## 8. Combine conditions (additional guided demonstration)

To combine NumPy conditions, use `&` for AND and `|` for OR. Place each comparison in parentheses. For example, values **greater than 6 and less than 11**:

In [7]:
middle_values = arr[(arr > 6) & (arr < 11)]
print("Values strictly between 6 and 11:", middle_values)
assert np.array_equal(middle_values, np.array([7, 8, 9, 10]))

Values strictly between 6 and 11: [ 7  8  9 10]


## 9. Final checks and expected output

| Expression | Expected result |
|---|---|
| `complex_a.shape` | `(10,)` |
| `complex_a.dtype.kind` | `'c'` (complex) |
| `steps` | `[0, 8, 16, 24, 32, 40]` |
| `arr.shape` | `(3, 4)` |
| `arr[1, :]` | `[5, 6, 7, 8]` |
| `arr[arr > 6]` | `[7, 8, 9, 10, 11, 12]` |

**Common mistakes:** Forgetting that `arange` excludes its stop; indexing the second row with `2`; attempting an impossible reshape; or writing `and` instead of `&` for NumPy Boolean arrays.

## 10. Review questions (with model answers)

**Q1. What do `ndim`, `shape`, `size` and `dtype` mean?** Number of dimensions, length of each dimension, total number of elements and element data type.

**Q2. Why is `reshape(5, 3)` invalid for twelve elements?** It requires fifteen elements, but the original array has only twelve.

**Q3. What does `arr[1, :]` return?** The entire second row.

**Q4. Why use Boolean indexing?** To select only values or rows satisfying a condition without writing an explicit loop.

**Optional extension:** Select the third column, find all even numbers, and reshape the original twelve values into `(4, 3)`.