## 1. Problem and learning goals

A data analyst receives two numerical matrices and must calculate, compare and summarise their values.

**Tasks from the slides**
1. Create two `3 × 3` arrays, ensuring denominators are non-zero.
2. Perform addition, subtraction, multiplication and division.
3. Calculate the overall total, **row sums** and **column means**.
4. Compare element-wise multiplication (`*`) with matrix multiplication (`@`).

**Deliverable:** Display and interpret each result, including `axis=0` and `axis=1`.

## 2. Create the input matrices

We follow the slide solution exactly: `a` contains the numbers 1 to 9 arranged into three rows, and `b` contains the number 2 in every position.

Both matrices have shape `(3, 3)`. Since `b` contains no zeros, `a / b` is safe.

In [1]:
import numpy as np

a = np.arange(1, 10).reshape(3, 3)
b = np.full((3, 3), 2)

print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nShapes:", a.shape, b.shape)

assert a.shape == b.shape == (3, 3)
assert np.all(b != 0), "Cannot divide by zero"

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array b:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]

Shapes: (3, 3) (3, 3)


## 3. Task 2 — Element-wise arithmetic

For arrays with matching shapes, NumPy applies `+`, `-`, `*` and `/` **position by position**. For example, the top-left element of `a + b` is `1 + 2 = 3`.

**Important:** `a * b` means element-wise multiplication, **not** matrix multiplication.

In [2]:
added = a + b
subtracted = a - b
multiplied = a * b
divided = a / b

print("Addition (a + b):\n", added)
print("\nSubtraction (a - b):\n", subtracted)
print("\nElement-wise multiplication (a * b):\n", multiplied)
print("\nElement-wise division (a / b):\n", divided)

Addition (a + b):
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Subtraction (a - b):
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Element-wise multiplication (a * b):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Element-wise division (a / b):
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


## 4. Check arithmetic against expected values

Assertions make the solution testable. For floating-point values, `np.testing.assert_allclose` is preferable to checking exact binary equality.

In [3]:
np.testing.assert_array_equal(added, a + 2)
np.testing.assert_array_equal(subtracted, a - 2)
np.testing.assert_array_equal(multiplied, 2 * a)
np.testing.assert_allclose(divided, a / 2)
print("All four arithmetic operations passed validation.")

All four arithmetic operations passed validation.


## 5. Task 3 — Calculate the total

`a.sum()` adds **all nine elements** of the matrix. Here the total is:

\[1+2+3+4+5+6+7+8+9=45\]

In [4]:
overall_total = a.sum()
print("Total of all values in a:", overall_total)
assert overall_total == 45

Total of all values in a: 45


## 6. Understand `axis=0` and `axis=1`

An axis indicates **which dimension is collapsed** by an aggregation:

- `axis=0` reduces **down the rows**, returning **one result per column**.
- `axis=1` reduces **across the columns**, returning **one result per row**.

For the matrix `a`:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Row sums are `[6, 15, 24]`, while column means are `[4.0, 5.0, 6.0]`.

In [5]:
row_sums = a.sum(axis=1)
column_means = a.mean(axis=0)

print("Row sums (axis=1):", row_sums)
print("Column means (axis=0):", column_means)

np.testing.assert_array_equal(row_sums, np.array([6, 15, 24]))
np.testing.assert_allclose(column_means, np.array([4.0, 5.0, 6.0]))

Row sums (axis=1): [ 6 15 24]
Column means (axis=0): [4. 5. 6.]


## 7. Task 4 — Compare `a * b` and `a @ b`

**Element-wise multiplication** multiplies corresponding positions: `(a * b)[0, 0] = 1 × 2 = 2`.

**Matrix multiplication** takes dot products of rows from `a` with columns from `b`:

\[(a @ b)_{0,0} = 1\times2 + 2\times2 + 3\times2 = 12\]

Matrix multiplication is defined only when the number of columns in the first matrix equals the number of rows in the second.

In [6]:
elementwise_product = a * b
matrix_product = a @ b

print("Element-wise product (a * b):\n", elementwise_product)
print("\nMatrix product (a @ b):\n", matrix_product)
print("\nTop-left element, *:", elementwise_product[0, 0])
print("Top-left element, @:", matrix_product[0, 0])

assert elementwise_product[0, 0] == 2
assert matrix_product[0, 0] == 12
assert not np.array_equal(elementwise_product, matrix_product)

Element-wise product (a * b):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix product (a @ b):
 [[12 12 12]
 [30 30 30]
 [48 48 48]]

Top-left element, *: 2
Top-left element, @: 12


## 8. Validate the matrix product

Because each column of `b` is `[2, 2, 2]`, each entry in a product row is twice the corresponding **row sum of `a`**.

Expected result:

```text
[[12, 12, 12],
 [30, 30, 30],
 [48, 48, 48]]
```

In [7]:
expected_matrix_product = np.array([
    [12, 12, 12],
    [30, 30, 30],
    [48, 48, 48],
])
np.testing.assert_array_equal(matrix_product, expected_matrix_product)
print("Matrix multiplication passed validation.")

Matrix multiplication passed validation.


## 9. Additional demonstration — Broadcasting

Broadcasting allows compatible shapes to work together without manually copying values. Here the shape `(3,)` row vector is added to every row of the `(3, 3)` matrix.

This is a **short extension**, not an additional requirement in the activity.

In [8]:
adjustment = np.array([10, 20, 30])
adjusted = a + adjustment

print("Adjustment shape:", adjustment.shape)
print("Adjusted matrix:\n", adjusted)
np.testing.assert_array_equal(adjusted[0], np.array([11, 22, 33]))

Adjustment shape: (3,)
Adjusted matrix:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


## 10. Expected results and interpretation

| Operation | Expected result |
|---|---|
| `a.sum()` | `45` |
| `a.sum(axis=1)` | `[6, 15, 24]` |
| `a.mean(axis=0)` | `[4., 5., 6.]` |
| `(a * b)[0, 0]` | `2` |
| `(a @ b)[0, 0]` | `12` |
| `(a @ b).shape` | `(3, 3)` |

**Common mistakes:** Confusing `*` with `@`, mixing up axis directions, ignoring incompatible shapes and dividing by zero.

## 11. Review questions (with model answers)

**Q1. What is the difference between `*` and `@`?** `*` multiplies matching elements; `@` performs matrix multiplication using row–column dot products.

**Q2. What does `sum(axis=0)` produce?** One sum per **column**.

**Q3. What does `sum(axis=1)` produce?** One sum per **row**.

**Q4. How do you avoid division by zero?** Check that the denominator has no zero values (or explicitly handle zeros using a mask and an appropriate policy).

**Optional extension:** Change `b` to a matrix containing different non-zero values and predict the top-left entry of `a @ b` before running the code.